#application: inprodsite # Use `--project=inprodsite` when you `gcloud app deploy`.
#version: upend # Use `--version=upend` when you `gcloud app deploy`.
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /.*\.(x|ht)ml
  script: redirect.site

- url: /game_assets/?.*
  script: game_assets.site

- url: /games/?.*
  script: games.site

- url: /admin/?.*
  script: admin.site

- url: /.*
  script: main.site
